mysql:
  dns: root:JIMbnmkpsmysql123@tcp(127.0.0.1:3306)/ginchat?charset=utf8mb4&parseTime=True&loc=Local
redis:
  addr: "localhost:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30
port:
  server: ":8081"
  udp: 3000
timeout:
  DelayHeartbeat: 3
  HeartbeatHz: 6
  HeartbeatMaxTime: 30